post/urls.py
from django.urls import path

from post import views

app_name = "post"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('<int:pk>/detail', views.post_detail, name='post_detail'),
    path('<int:pk>/edit', views.post_edit, name='post_edit'),
    path('<int:pk>/delete', views.post_delete, name='post_delete'),
]

qna/urls.py
from django.urls import path
from qna import views

app_name = "qna"

urlpatterns = [
    path('', views.start, name='start'), # 첫사용자라면 나레이션 이동, 기사용자라면 답변하지 않은 질문 페이지로 이동
    path('<int:index>/write/', views.write_answer, name='write_answer'), # 답변
    path('<int:qrecord>/question/', views.show_question, name='show_question'),
    path('<int:index>/answer/', views.show_answer, name='show_answer'),
    path('<int:pIndex>/toPage', views.toPage, name='toPage'),
]

swim12/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

]

yuyoung/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('qna/', include('qna.urls')),
    path('post/', include('post.urls')),
]

post/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User=get_user_model()

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE) # 유저 매핑

post/views.py
from datetime import timezone

from django.shortcuts import render, redirect

from post.models import Post


# 전체 게시글 조회
def post_list(request):
    if request.user.is_staff:
        posts = Post.objects.all()
        return render(request, 'post_list.html', context={'posts': posts})

    return redirect('user:mainPage')

# 게시글 생성
def post_create(request):
    if not request.user.is_authenticated:
        return redirect('user:mainPage')

    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        writer = request.user

        Post.objects.create(
            title = title,
            content = content,
            writer = writer,
        )

        return redirect('post:post_list')

    return render(request, 'post_create.html')

# 상세 게시글 조회
def post_detail(request, pk):
    if not request.user.is_authenticated:
        return redirect('user:mainPage')

    post = Post.objects.get(pk=pk)
    return render(request, 'post_detail.html', context={'post': post})

# 게시글 수정
def post_edit(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('post:post_list')
    else:
        return render(request, 'post_create.html', context={'post': post})

# 게시글 삭제
def post_delete(request, pk):
    posts = Post.objects.all()

    if request.method == 'GET':
        post = Post.objects.get(pk=pk)
        post.delete()
    return render(request, 'post_list.html', context={'posts': posts})

post/templates/post_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>게시글 생성</title>
    <link rel="stylesheet" href="/static/css/post_create.css" />
  </head>
  <body>
    <div id="bigbg">
      <div id="container">
        <div id="goBack" style="position: absolute; top: 61px; left: 25px">
          <a href="http://127.0.0.1:8000/post/"
            ><img src="/static/Image/backBtn.png"
          /></a>
        </div>
        <img src="/static/Image/write.png" id="textBox" />
        <form method="POST">
          {% csrf_token %}
          <input
            type="text"
            name="title"
            id="title"
            placeholder="제목을 적어주세요"
            value="{{ post.title }}"
          />
          <textarea
            id="text"
            placeholder="당신 또는 다른 사람에게 전하고 싶은 이야기를 적어주세요."
            type="textarea"
            name="content"
            value="{{ post.content }}"
          ></textarea>
          <div id="box">
            <button id="backBtn" type="submit">작성하기</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

post/templates/post_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Post Details</title>
    <link rel="stylesheet" href="/static/css/post_detail.css" />
  </head>
  <body>
    <div id="bigbg">
      <div id="container">
        <img src="/static/Image/GuestBook.png" id="textBox" />
        <div id="title">{{ post.title }}</div>
        <div id="info">
          <div id="username">{{ post.writer.username }}</div>
          <div id="time">작성시간: {{post.created_at}}</div>
        </div>
        <div id="content">{{ post.content }}</div>
        <div id="backBtn">
          <a href="http://127.0.0.1:8000/post">돌아가기</a>
        </div>
      </div>
    </div>
  </body>
</html>

post/templates/post_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Post List</title>
    <link rel="stylesheet" href="/static/css/post_list.css" />
  </head>
  <body>
    <div id="bigbg">
      <div id="container">
        <div id="toMain" style="position: absolute; top: 61px; left: 25px">
          <a href="http://127.0.0.1:8000/"
            ><img src="/static/Image/mainBtn.png"
          /></a>
        </div>
        <img src="/static/Image/GuestBook.png" id="textBox" />
        {% for post in posts %}
        <div id="guest-list">
          <div id="text">
            <div id="title">
              <a href="{% url 'post:post_detail' pk=post.pk%}"
                >{{ post.title }}</a
              >
            </div>
            <div id="username">{{ post.writer.username }}</div>
          </div>
          {% if request.user == post.writer %}
          <div id="btn">
            <form method="GET" action="{% url 'post:post_edit' pk=post.pk %}">
              <button button type="submit">
                <img id="pencil" src="/static/Image/pencil.png" />
              </button>
            </form>
            <form method="GET" action="{% url 'post:post_delete' pk=post.pk %}">
              <button type="submit">
                <img id="trashcan" src="/static/Image/trashcan.png" />
              </button>
            </form>
          </div>
          {% endif %}
        </div>
        {% endfor %}
        <div id="writeBtn">
          <a href="http://127.0.0.1:8000/post/create">작성하기</a>
        </div>
      </div>
    </div>
  </body>
</html>