qna/urls.py
from django.urls import path
from qna import views

app_name = "qna"

urlpatterns = [
    path('', views.start, name='start'), # 첫사용자라면 나레이션 이동, 기사용자라면 답변하지 않은 질문 페이지로 이동
    path('<int:index>/write/', views.write_answer, name='write_answer'), # 답변
    path('<int:qrecord>/question/', views.show_question, name='show_question'),
    path('<int:index>/answer/', views.show_answer, name='show_answer'),
    path('<int:pIndex>/toPage', views.toPage, name='toPage'),
]

swim12/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user import views

app_name = "user"

urlpatterns = [
    path('', views.mainPage, name='mainPage'),
    path('loginPage/', views.loginPage, name='loginPage'),
    path('signupPage/', views.signupPage, name='signupPage'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('signup/', views.signup, name='signup')
]

yuyoung/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('qna/', include('qna.urls')),
    path('post/', include('post.urls')),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    qrecord = models.IntegerField(default=0)

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

User = get_user_model()

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

user/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.hashers import check_password
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect

from qna.views import create_question
from user.models import User


# 메인 페이지
def mainPage(request):
    return render(request, 'main.html')

# 로그인 페이지
def loginPage(request):
    return render(request, 'login.html')

# 회원가입 페이지
def signupPage(request):
    return render(request, 'signup.html')

# 로그인
# def login(request):
#     if request.method =='GET':
#         return render(request, 'login.html')
#     elif request.method == 'POST':
#         username = request.POST.get('username', None)
#         password = request.POST.get('password', None)
#
#         err_data = {}
#         if not(username and password):
#             err_data['error'] = '모든 값을 입력해 주세요.'
#         else:
#             user = User.objects.get(username=username)
#             if check_password(password, user.password):
#                 request.session['user'] = user.id
#                 return redirect('user:mainPage')
#             else:
#                 err_data['error'] = '비밀번호가 일치하지 않습니다.'
#         return render(request, 'login.html', err_data)

def signup(request):
    if request.method == "GET":
        return (request, 'signup.html')

    elif request.method == "POST":
        username = request.POST.get('username', None)
        password1 = request.POST.get('password1', None)
        password2 = request.POST.get('password2', None)

        user = User(
            username=username,
            password=make_password(password1)
        )
        if not (username and password1 and password2):
            err_data = '모든 항목을 입력해주세요.'
            return render(request, 'signup.html', context={'error': err_data})

        if User.objects.all().filter(username=username).exists() == True:
            err_data = '이미 존재하는 아이디입니다.'
            return render(request, 'signup.html', context={'error': err_data})

        if password1 != password2:
            err_data = '비밀번호가 다릅니다.'
            return render(request, 'signup.html', context={'error': err_data})

        else:
            user.save()
            create_question(user)

            return redirect('user:mainPage')

user/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Log In</title>
    <link rel="stylesheet" href="{% static '/css/login.css' %}" />
  </head>
  <body>
    <div id="bigbg">
      <div id="container">
        <div id="goBack" style="position: absolute; top: 61px; left: 25px">
          <a href="http://127.0.0.1:8000/"
            ><img src="/static/Image/backBtn.png"
          /></a>
        </div>
        <div id="whiteBox">
          <img src="../../static/Image/Login.png" id="textBox" />
          <form method="POST" action="{% url 'user:login' %}">
            {% csrf_token %}
            <div id="inputBox">
              <div id="idLabel">
                <span>아이디</span>
              </div>
              <input
                type="text"
                name="username"
                value="{{ form.username.value|default_if_none:'' }}"
                id="idInput"
              />
            </div>
            <div id="inputBox">
              <div id="pwLabel">
                <span>비밀번호</span>
              </div>
              <input
                type="password"
                name="password"
                value="{{ form.password.value|default_if_none:'' }}"
                id="pwInput"
              />
            </div>
            <button type="submit" id="loginBtn">로그인</button>
          </form>
          <div id="errorMsg" style="visibility: hidden">{{ error }}</div>
        </div>
      </div>
    </div>
  </body>
</html>

user/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Main</title>
    <link rel="stylesheet" href="{% static '/css/main.css' %}" />
  </head>
  <body>
    <div id="bigbg">
      <div id="container">
        <div id="click">거울 속을 눌러보세요</div>
        <form method="POST" action="{% url 'qna:start' %}">
          {% csrf_token %}
          <!-- 거울 속 클릭하면 서비스 시작 -->
          <button type="submit" id="ctitle">遊 泳</button>
        </form>
        <div id="ktitle">유영</div>
        <div id="btnbox">
          <span id="loginBtn">
            <a href="http://127.0.0.1:8000/loginPage/">로그인</a></span
          >
          <span>|</span>
          <span id="registerBtn">
            <a href="http://127.0.0.1:8000/signupPage/">회원가입</a></span
          >
        </div>
      </div>
    </div>
  </body>
</html>

user/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static '/css/signup.css' %}" />
  </head>
  <body>
    <div id="bigbg">
      <div id="container">
        <div id="goBack" style="position: absolute; top: 61px; left: 25px">
          <a href="http://127.0.0.1:8000/"
            ><img src="/static/Image/backBtn.png"
          /></a>
        </div>
        <div id="whiteBox">
          <img src="../../static/Image/Register.png" id="textBox" />
          <form method="POST" action="{% url 'user:signup' %}">
            {% csrf_token %}
            <div id="inputBox">
              <div id="idLabel">
                <span>아이디</span>
              </div>
              <input
                type="text"
                name="username"
                value="{{ form.username.value|default_if_none:'' }}"
                id="idInput"
              />
            </div>
            <div id="inputBox">
              <div id="pwLabel">
                <span>비밀번호1</span>
              </div>
              <input
                type="password"
                name="password1"
                value="{{ form.password1.value|default_if_none:'' }}"
                id="pwInput"
              />
            </div>
            <div id="inputBox">
              <div id="pwLabel">
                <span>비밀번호2</span>
              </div>
              <input
                type="password"
                name="password2"
                value="{{ form.password2.value|default_if_none:'' }}"
                id="pwInput"
              />
            </div>
            <button type="submit" id="registerBtn">회원가입</button>
          </form>
          <div id="errorMsg" style="visibility: hidden">{{ error }}</div>
        </div>
      </div>
    </div>
    <script src="/static/js/signup.js"></script>
  </body>
</html>